name: 豪shi
description: 豪shi的碎碎念
author: 豪shi
author_email: francisjiang@outlook.com

category_dir: /
url: http://franj.me

#markdown: rdiscount
markdown: redcarpet
pygments: true

#permalink: pretty

